services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app_network

  api:
    build: .
    container_name: flask_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/users || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
